[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "gcc"]

[phases.install]
cmds = ["cd railway-api && python -m pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Skipping Node.js build'"]

[start]
cmd = "cd railway-api && python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT"