[build]
builder = "nixpacks"
buildCommand = "cd railway-api && python -m pip install -r requirements.txt"

[deploy]
startCommand = "cd railway-api && python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/api/health"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10